# Generated by Django 2.2.3 on 2019-08-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190816_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='a', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
