# Generated by Django 2.2.3 on 2019-08-16 00:40

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('pic', '750x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
