# Generated by Django 2.2.3 on 2019-08-16 02:31

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_article_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('pic', '750x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('pic', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
